### ISSUE TITLE
Add links to reports

### ISSUE THREAD

**Issue by rishiraje** [divy-work/covid19-pune#1]
Hi,

It is good that you are creating a central repository for Pune.

Please add links to the reports that you make. This way the users can check the sources.

**Comment by littledivy** [comment]
Sure! I'll add report links. Thanks for informing.
You are always welcome to create a Pull Request here :)

**Comment by littledivy** [comment]
@rishiraje thanks for opening the issue, I've added the links to news reports in the latest commits.
